export const FETCH_ITEM_PRODUCT_REQUEST = 'FETCH_ITEM_PRODUCT_REQUEST';
export const FETCH_ITEM_PRODUCT_FAILURE = 'FETCH_ITEM_PRODUCT_FAILURE';
export const FETCH_ITEM_PRODUCT_SUCCESS = 'FETCH_ITEM_PRODUCT_SUCCESS';
