export const ORDER_INPUT_PHONE = 'ORDER_INPUT_PHONE';
export const ORDER_INPUT_ADDRESS = 'ORDER_INPUT_ADDRESS';
export const ORDER_AGREEMENT = 'ORDER_AGREEMENT';


export const ORDER_SUBMIT_REQUEST = 'ORDER_SUBMIT_REQUEST';
export const ORDER_SUBMIT_SUCCESS = 'ORDER_SUBMIT_SUCCESS';
export const ORDER_SUBMIT_FAILURE = 'ORDER_SUBMIT_FAILURE';

export const ORDER_DEFAULT = 'ORDER_DEFAULT';

