export const FETCH_CATALOG_REQUEST = 'FETCH_CATALOG_REQUEST';
export const FETCH_CATALOG_FAILURE = 'FETCH_CATALOG_FAILURE';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const ACTUAL_CATEGORIES_ID = 'ACTUAL_CATEGORIES_ID';